# Generated by Django 4.2.21 on 2025-05-21 06:57

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_name', models.CharField(default='', max_length=25)),
                ('category', models.CharField(default='', max_length=25)),
                ('sub_category', models.CharField(default='', max_length=25)),
                ('price', models.IntegerField(default=0)),
                ('description', models.CharField(default='', max_length=100)),
                ('published_date', models.DateField()),
                ('image', models.FileField(default='', upload_to='static/blog')),
            ],
        ),
    ]
