# Generated by Django 4.2.21 on 2025-05-24 04:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_alter_product_category_alter_product_description_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='number_of_stock',
            field=models.IntegerField(default=0),
        ),
    ]
