# Generated by Django 4.2.21 on 2025-05-24 04:27

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_product_number_of_stock'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='number_of_stock',
            field=models.IntegerField(validators=[django.core.validators.MinValueValidator(0)]),
        ),
    ]
