# Generated by Django 4.2.21 on 2025-05-27 05:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0007_alter_product_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.CharField(choices=[('Fashion', 'Fashion'), ('Accessories', 'Accessories'), ('Electronics', 'Electronics'), ('Home', 'Home'), ('Kitchen', 'Kitchenware'), ('Grocery', 'Grocery'), ('Beauty', 'Beauty'), ('Toys', 'Toys'), ('Sports', 'Sports'), ('Stationery', 'Stationery'), ('Automotive', 'Automotive'), ('Pet', 'Pet'), ('Other', 'Other')], default='Other', max_length=20),
        ),
    ]
