# Generated by Django 4.2.21 on 2025-05-27 07:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0008_alter_product_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='image',
            field=models.FileField(default='', help_text='Recommended image size: 230×200 pixels', upload_to='blog/images/'),
        ),
    ]
