# Generated by Django 4.2.21 on 2025-06-02 05:28

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0010_alter_product_description_alter_product_product_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='product_name',
            field=models.CharField(default='', max_length=100, validators=[django.core.validators.MinLengthValidator(20)]),
        ),
    ]
