# Generated by Django 4.2.21 on 2025-06-11 11:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0013_profile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.CharField(choices=[('Electronics', 'Electronics'), ('Fashion', 'Fashion'), ('Home & Kitchen', 'Home & Kitchen'), ('Beauty & Personal Care', 'Beauty & Personal Care'), ('Grocery & Gourmet Foods', 'Grocery & Gourmet Foods'), ('Books & Stationery', 'Books & Stationery'), ('Toys, Baby Products & Kids', 'Toys, Baby Products & Kids'), ('Appliances', 'Appliances'), ('Sports, Fitness & Outdoors', 'Sports, Fitness & Outdoors'), ('Automotive', 'Automotive'), ('Health & Household', 'Health & Household'), ('Jewellery', 'Jewellery'), ('Pet Supplies', 'Pet Supplies'), ('Industrial & Scientific', 'Industrial & Scientific'), ('Other', 'Other')], default='Other', max_length=30),
        ),
        migrations.AlterField(
            model_name='product',
            name='sub_category',
            field=models.CharField(blank=True, default='', max_length=50),
        ),
    ]
