# Generated by Django 4.2.21 on 2025-06-12 04:49

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0014_alter_product_category_alter_product_sub_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='max_order_quantity',
            field=models.IntegerField(default=10, validators=[django.core.validators.MinValueValidator(1)]),
        ),
    ]
